apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - namespace.yaml
  - crds/compositeresourcedefinitions.yaml
  - crds/compositions.yaml
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: crossplane
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-environment-configs
