apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crossplane/providers/gcp.yaml
  - gcp/compositions/gke-autopilot.yaml
  # stevedores-gke cluster claim removed - cluster decommissioned
