apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/crds/bundle.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/manifests/namespace.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/manifests/service-account.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/manifests/cluster-role.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/manifests/cluster-role-binding.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/manifests/deployment.yaml
